### ISSUE TITLE
Swift 3 version would be so nice !

### ISSUE THREAD

**Issue by nmDejamobile** [andysmart/Timberjack#15]
As Swift 3 is out, a compatible version of EVURLCache would be nice.
For the moment I embed the lib in my project and convert it to Swift 3.

**Comment by 0x384c0** [comment]
it seems the developer has died
and library will no longer be updated

**Comment by kolisko** [comment]
FYI my twitter chat

me: Hi Andy, sorry to contact you here. I would like to ask you - any chance to add TimberJack swift3 pull reqs on github? Tx

Andy: hey Michal! Sorry, it’s been a little neglected to be honest, I’ll be reviewing them over the weekend 🙂

me: thanks a lot!

**Comment by gilthonweapps** [comment]
You can use my fork: https://github.com/gilthonweapps/Timberjack

**Comment by andysmart** [comment]
Swift 3.0 now supported in `v.0.0.3` thanks for your patience folks

**Comment by linakis** [comment]
v.0.0.2 is still in pod repo

**Comment by leonirqranio** [comment]
Last version not updated in Cocoapods repo
